reattach
fizo99/Nokia-PK-2022 pull request #13
Opened 2022-04-11 12:00 UTC by Guurkha

2022-04-11 12:26 UTC, fizo99 requested changes

2022-04-11 12:26 UTC, fizo99 commented on UE/Tests/Application/ApplicationTestSuite.cpp
> +//reatach
do wyrzucenia komentarz

2022-04-11 12:26 UTC, fizo99 commented on UE/Application/States/ConnectedState.cpp
>  namespace ue
linijka wolnego miejsca pomidzy include a namespace by sie przydala

2022-04-11 12:26 UTC, fizo99 commented on UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +    common::ITransport::DisconnectedCallback DisconnectedCallback;
zmien na disconnectedCallback

2022-04-11 12:26 UTC, fizo99 commented on UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +                .WillOnce(SaveArg<0>(&DisconnectedCallback));
disconnectedCallback (camelCase)

2022-04-11 12:45 UTC, ganados commented on UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +    common::ITransport::DisconnectedCallback DisconnectedCallback;
ale tylko nazwę, nie klasę

2022-04-11 12:45 UTC, ganados commented on UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +
niepotrzebny enter

2022-04-18 19:01 UTC, closed without merging

2022-04-18 19:01 UTC, Guurkha commented
changes done